### ISSUE TITLE
Reliability - nothing shows up for NJ Transit Ridership

### ISSUE THREAD

**Issue by smoran3** [dvrpc/RTPS#32] opened 2019-05-01 12:02 UTC
on Route detail tab, when you add a NJT route to the filter and turn on NJT Ridership, nothing appears. Can you find out if this is a broken connection or if there is something missing on the back end that I need to give you?

**Comment by mmolta** [comment] 2019-05-16 18:11
The NJT Ridership appears to be broken because the vector tiles only have the following NJ Transit lines:

- "313"
- "315"
- "317"
- "403"
- "404"
- "405"
- "407"
- "408"
- "409"
- "413"
- "418"
- "419"
- "551"

Filtering for any of the above will work, but any other NJT line will not render anything becasue as far as mapbox knows, they don't exist.

We need to update the vector tiles to include the rest of the NJT lines and then this issue will solve itself.

**Comment by smoran3** [comment] 2019-05-16 18:32
Vector tiles is something Robert set up - I don't actually know how to do this. Do you?

**Comment by mmolta** [comment] 2019-05-17 14:00
Yea, I can make the update. I'll close the issue when it's done and confirmed that everything works.

**Comment by crvanpollard** [comment] 2019-06-27 17:13
@smoran3 @mmolta please double check the web app to see if the missing NJT routes are now visible since  the Vector Tiles have been updated

**Comment by smoran3** [comment] 2019-06-27 17:18
Same thing here. Zoomed out, they don't show. More show up as I zoom in, but some show up almost grayed out.
![image](https://user-images.githubusercontent.com/22378781/60286712-155ba500-98de-11e9-987c-2e281ddec06f.png)

**Comment by mmolta** [comment] 2019-06-27 17:40
issue is resolved, vt cache will persist for a little bit

**Closed as completed by mmolta** 2019-06-27 17:40 UTC
Labels: bug
